# Generated by Django 6.0.2 on 2026-03-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('class_owner', 'Class Owner'), ('admin', 'Admin')], max_length=20),
        ),
    ]
